# Generated by Django 4.2.1 on 2023-05-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_school_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddField(
            model_name='report',
            name='rank',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
