# Generated by Django 4.2.1 on 2023-06-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_report_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='etc_good',
        ),
        migrations.AddField(
            model_name='report',
            name='user_country_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='wordCloudUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
