# Generated by Django 4.2.1 on 2023-06-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_remove_report_etc_good_report_user_country_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='now_cost',
            new_name='now_dorm_cost',
        ),
    ]
