# Generated by Django 4.2.1 on 2023-06-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_rename_now_cost_report_now_dorm_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='pre_visa_type',
        ),
        migrations.AddField(
            model_name='report',
            name='visa_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
