# Generated by Django 4.2.1 on 2023-06-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_remove_report_pre_visa_type_report_visa_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='pre_visa_apply_duration',
            new_name='visa_apply_duration',
        ),
    ]
