# Generated by Django 4.2.1 on 2023-06-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0011_rename_pre_visa_apply_duration_report_visa_apply_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='pre_visa_how',
            new_name='visa_how',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='pre_visa_ready_check',
            new_name='visa_ready_check',
        ),
    ]
