# Generated by Django 4.2.1 on 2023-06-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0012_rename_pre_visa_how_report_visa_how_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='visa_apply_duration',
            new_name='visa_issue_time',
        ),
    ]
