# Generated by Django 4.2.1 on 2023-06-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0013_rename_visa_apply_duration_report_visa_issue_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='user_type',
            new_name='program_type',
        ),
    ]
