# Generated by Django 4.2.1 on 2023-06-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0014_rename_user_department_report_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='user_country_code',
            new_name='country_code',
        ),
    ]
