# Generated by Django 4.2.1 on 2023-06-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0015_rename_user_country_report_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user_duration',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='user_university',
            new_name='university',
        ),
    ]
