# Generated by Django 4.2.1 on 2023-06-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0017_rename_visa_how_report_visa_issuance_procedure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='pre_class_register',
            new_name='class_register',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='pre_dorm_register',
            new_name='dorm_register',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='visa_ready_check',
            new_name='pre_departure_preparation',
        ),
    ]
