# Generated by Django 4.2.1 on 2023-06-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0018_rename_pre_class_register_report_class_register_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='now_move_how',
            new_name='airport_to_campus_mobility',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='now_move_time',
            new_name='airpotr_to_campus_time',
        ),
    ]
