# Generated by Django 4.2.1 on 2023-06-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0022_rename_course_how_report_course_procedure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='post_dorm_end',
            new_name='dorm_leaving',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='post_flight',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='etc_feel',
            new_name='impression',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='post_ready_check',
            new_name='pre_entry_preparation',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='post_how_end',
            new_name='program_end_procedure',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='rank',
            new_name='satisfaction',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='ect_say',
            new_name='suggestion',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='wordCloudUrl',
            new_name='word_cloud_url',
        ),
    ]
