# Generated by Django 4.2.1 on 2023-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0023_rename_post_dorm_end_report_dorm_leaving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='recommand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
