# Generated by Django 4.2.1 on 2023-06-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0024_alter_article_comment_alter_article_recommand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_university',
            new_name='university',
        ),
    ]
