# Generated by Django 4.2.1 on 2023-06-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0026_article_author_alter_article_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='user',
        ),
    ]
