# Generated by Django 4.2.1 on 2023-06-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0027_rename_author_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
    ]
